version: '3.8'

services:
  api:
    build: .
    ports:
      - "8004:8004"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL}
      - CLAUDE_TEMPERATURE=${CLAUDE_TEMPERATURE}
      - CLAUDE_MAX_TOKENS=${CLAUDE_MAX_TOKENS}
      - DEBUG=${DEBUG}
      - TESTING=${TESTING}
      - MAX_FINDINGS_PER_SUBMISSION=${MAX_FINDINGS_PER_SUBMISSION}
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge